Repository fastcampus-final/go-together-fe, pull requests merged in 2023-03, with the labels that each got.

#4 404페이지 구현
  package-lock.json
  package.json
  pages/404/index.tsx
  public/404page.json
Labels: feature

#6 develop 브랜치의 수정 사항을 main 브랜치에 반영
  package-lock.json
  package.json
  pages/404/index.tsx
  public/404page.json
Labels: deploy

#7 react-lottie 를 lottie-react로 교체
  package-lock.json
  package.json
  pages/404/index.tsx
Labels: fix

#8 main 브랜치에 develop 브랜치 수정사항 반영
  src/constants/routes.ts
Labels: deploy

#15 상품 컴포넌트 구현
  pages/product/index.tsx
  src/components/Product/index.tsx
  src/components/common/Image.tsx
  src/hooks/useLikeList.tsx
  src/interfaces/product.ts
  src/mocks/handlers/product.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/utils/format.ts
Labels: feature

#17 로그인 기능 추가 / docs: 회원가입 페이지 루트명 변경
  package-lock.json
  package.json
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/mypage/info.tsx
  pages/mypage/withdrawal.tsx
  pages/product/index.tsx
  pages/signup/index.tsx
  pages/signup/success.tsx
  pages/survey/index.tsx
  src/components/Product/index.tsx
  src/components/common/Image.tsx
  src/components/common/Input.tsx
  src/components/common/Loading.tsx
  src/components/common/PrivateRouter.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/constants/messages.ts
  src/hooks/useLikeList.tsx
  src/interfaces/loginResgister.ts
  src/interfaces/product.ts
  src/mocks/handlers/product.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/utils/format.ts
Labels: feature, docs

#20 상품 검색 페이지 구현중
  package-lock.json
  package.json
  pages/product/index.tsx
  pages/search/index.tsx
  src/components/Product/index.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/layout/Layout.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: feature

#19 메인 페이지 구조 정리
  package-lock.json
  package.json
  pages/index.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#22 최근 검색어 저장 기능 구현
  package-lock.json
  package.json
  pages/product/index.tsx
  pages/search/index.tsx
  src/components/common/Modal.tsx
  src/components/layout/Layout.tsx
  src/constants/messages.ts
  src/interfaces/modal.ts
  src/store/index.tsx
  src/store/modal.tsx
  src/utils/storage.ts
Labels: feature

#24 여행 유형 테스트 페이지 레이아웃 설정
  pages/search/index.tsx
  pages/survey/index.tsx
  public/test.png
  src/components/common/Button.tsx
  src/components/layout/Navbar.tsx
  src/constants/routes.ts
  src/styles/theme.ts
Labels: feature

#26 장바구니 페이지 구현중 / 파비콘, 로고 이미지 추가 및 레이아웃에 적용
  pages/cart/index.tsx
  pages/index.tsx
  pages/product/index.tsx
  pages/search/index.tsx
  pages/survey/index.tsx
  public/favicon.ico
  public/logo-full.png
  public/logo.png
  src/api/instance.tsx
  src/components/Cart/CartItem.tsx
  src/components/common/PageTitle.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/hooks/useLikeList.tsx
  src/interfaces/cart.ts
  src/styles/theme.ts
Labels: feature, style

#29 레이아웃 작업
  package-lock.json
  package.json
  pages/cart/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/product/index.tsx
  pages/search/index.tsx
  pages/signup/index.tsx
  pages/survey/index.tsx
  public/favicon.ico
  public/logo-full.png
  public/logo.png
  public/test.png
  src/api/instance.tsx
  src/components/Cart/CartItem.tsx
  src/components/Product/index.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/PageTitle.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/Login_header.tsx
  src/components/layout/header/Logo_header.tsx
  src/components/layout/header/Mypage_header.tsx
  src/components/layout/header/Search_header.tsx
  src/components/layout/nav/NavList.tsx
  src/constants/messages.ts
  src/constants/routes.ts
  src/hooks/useLikeList.tsx
  src/interfaces/cart.ts
  src/interfaces/loginResgister.ts
  src/interfaces/modal.ts
  src/interfaces/myinfo.ts
  src/interfaces/nav_text.ts
  src/store/index.tsx
  src/store/modal.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/utils/storage.ts
Labels: feature

#35 장바구니 레이아웃 구현
  pages/cart/index.tsx
  src/components/Cart/CartItem.tsx
  src/components/common/Image.tsx
  src/interfaces/cart.ts
  src/utils/format.ts
Labels: feature

#38 관리자 페이지 초기 셋팅 진행중
  package-lock.json
  pages/_app.tsx
  pages/admin/banner/[id].tsx
  pages/admin/banner/form.tsx
  pages/admin/banner/index.tsx
  pages/admin/index.tsx
  pages/admin/order/[id].tsx
  pages/admin/order/form.tsx
  pages/admin/order/index.tsx
  pages/admin/product/[id].tsx
  pages/admin/product/category/[id].tsx
  pages/admin/product/category/form.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/form.tsx
  pages/admin/product/index.tsx
  pages/admin/review/[id].tsx
  pages/admin/review/form.tsx
  pages/admin/review/index.tsx
  pages/admin/user/[id].tsx
  pages/admin/user/form.tsx
  pages/admin/user/index.tsx
  pages/mypage/index.tsx
  src/components/common/Image.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/admin/AdminHeader.tsx
  src/components/layout/admin/AdminNavbar.tsx
  src/components/layout/header/Mypage_header.tsx
  src/constants/routes.ts
Labels: conf, feature, style

#37 전체적인 리팩토링
  pages/cart/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/mypage/info.tsx
  pages/order/index.tsx
  pages/signup/index.tsx
  pages/signup/success.tsx
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Logout.tsx
  src/components/Mypage/Withdrawal.tsx
  src/components/common/Input.tsx
  src/components/common/NotInput.tsx
  src/components/common/PasswordModal.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/nav/FlexGroup.tsx
  src/components/layout/nav/HoverGroup.tsx
  src/constants/messages.ts
  src/constants/navGroup.ts
  src/interfaces/inputProps.ts
  src/interfaces/navText.ts
  src/interfaces/notInputProps.ts
  src/interfaces/passwordModal.ts
  src/interfaces/withdrawal.tsx
Labels: refactor

#40 관리자 페이지 로그아웃 시 모든 쿠키 삭제
  src/components/layout/admin/AdminHeader.tsx
Labels: fix

#43 상세페이지 옵션 선택 파트 구현
  package-lock.json
  package.json
  pages/mypage/withdrawal.tsx
  pages/product/[id].tsx
  src/interfaces/product.ts
  src/mocks/handlers/productDetail.ts
Labels: feature

#42 예약페이지 기능 설정
  pages/mypage/index.tsx
  pages/order/index.tsx
  pages/signup/index.tsx
  src/components/Mypage/GetMyinfo.tsx
  src/components/Order/OrderItem.tsx
  src/components/common/Input.tsx
  src/components/common/PrivateRouter.tsx
  src/constants/messages.ts
  src/interfaces/inputProps.ts
Labels: feature

#45 마이페이지-내 정보 보기/수정 , 레아아웃, 로그인, 회원가입 페이지 리팩토링
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/mypage/info.tsx
  pages/mypage/withdrawal.tsx
  pages/order/index.tsx
  pages/signup/index.tsx
  src/components/Login/SearchPassword.tsx
  src/components/Login/apis.ts
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Logout.tsx
  src/components/Mypage/Withdrawal.tsx
  src/components/Mypage/apis.ts
  src/components/Mypage/function.ts
  src/components/SignIn/EmailInput.tsx
  src/components/SignIn/GenderInput.tsx
  src/components/SignIn/apis.ts
  src/components/SignIn/function.ts
  src/components/common/Input.tsx
  src/components/common/PasswordModal.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/apis.ts
  src/components/layout/nav/FlexGroup.tsx
  src/components/layout/nav/HoverGroup.tsx
  src/interfaces/inputProps.ts
  src/interfaces/loginResgister.ts
  src/interfaces/myinfo.ts
Labels: refactor

#47 전체적인 레이아웃 수정
  pages/cart/index.tsx
  pages/product/index.tsx
  pages/search/index.tsx
  pages/survey/index.tsx
  public/logo-full.png
  public/logo.png
  public/logo.svg
  src/components/Cart/CartItem.tsx
  src/components/Product/index.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/admin/AdminHeader.tsx
  src/components/layout/header/Logo_header.tsx
Labels: feature, refactor

#48 input컴포넌트 에러 수정
  pages/_app.tsx
  pages/mypage/index.tsx
  pages/mypage/withdrawal.tsx
  src/components/common/Input.tsx
Labels: fix

#52 Feat: 커뮤니티-리뷰, 공지사항 라우터 수정 및 더미데이터 생성
  pages/community/notice/index.tsx
  pages/community/review/index.tsx
  src/constants/routes.ts
  src/dummydata/communityReview.json
  src/interfaces/community.ts
Labels: feature

#53 검색 페이지 최근 검색어 관련 기능 구현
  package-lock.json
  package.json
  pages/_app.tsx
  pages/product/index.tsx
  pages/search/index.tsx
  pages/survey/index.tsx
  src/components/Product/ProductItem.tsx
  src/components/common/Image.tsx
  src/components/common/ScrollTop.tsx
  src/components/layout/Layout.tsx
  src/styles/GlobalStyle.tsx
  src/utils/storage.ts
Labels: feature

#54 마이페이지 랜덤 프로필 이미지 적용
  package-lock.json
  package.json
  pages/admin/product/category/edit.tsx
  pages/mypage/index.tsx
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Withdrawal.tsx
  src/styles/GlobalStyle.tsx
Labels: style

#55 [커뮤니티]여행 후기 목록 구현
  next.config.js
  package-lock.json
  package.json
  pages/community/review/index.tsx
  public/icons/Group.svg
  public/icons/edit.svg
  src/components/Community/CommunityRouter.tsx
  src/components/Community/ReviewItem.tsx
  src/dummydata/communityReview.json
  src/utils/format.ts
Labels: feature

#56 전체적인 레이아웃 수정
  pages/cart/index.tsx
  pages/mypage/index.tsx
  pages/mypage/order/index.tsx
  pages/mypage/review/index.tsx
  pages/mypage/wish/index.tsx
  pages/survey/index.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/Login_header.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/Mypage_header.tsx
Labels: style

#57 마이페이지 관심상품 목록 출력
  package-lock.json
  pages/cart/index.tsx
  pages/mypage/wish/index.tsx
  pages/product/index.tsx
  pages/survey/index.tsx
  src/components/Cart/CartCard.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Product/ProductCard.tsx
  src/components/common/Image.tsx
  src/styles/muiTheme.ts
Labels: feature

#58 디자인 가이드 적용
  src/components/Mypage/Wish/WishCard.tsx
  src/components/common/PageTitle.tsx
  src/styles/GlobalStyle.tsx
  src/styles/muiTheme.ts
Labels: conf, style

#59 여행 유형 테스트 스텝퍼 설정
  pages/survey/index.tsx
  src/components/Product/ProductCard.tsx
  src/components/common/ScrollTop.tsx
Labels: feature
