Repository fastcampus-final/go-together-fe, pull requests merged in 2023-04, with the labels that each got.

#61 커뮤니티-여행후기 모바일 화면 수정 및 페이지네이션 추가
  package-lock.json
  package.json
  pages/community/review/[id].tsx
  pages/community/review/add.tsx
  pages/community/review/index.tsx
  pages/review/index.tsx
  src/components/Community/ReviewItem.tsx
  src/constants/routes.ts
Labels: feature, style

#63 [커뮤니티] 알려드려요(공지사항) 구현
  pages/community/notice/[id].tsx
  pages/community/notice/index.tsx
  pages/community/review/[id].tsx
  src/components/Community/CommunityRouter.tsx
  src/components/Community/NoticeItem.tsx
  src/constants/routes.ts
  src/dummydata/communityNotice.json
  src/dummydata/communityReview.json
Labels: feature

#65 키워드로 상품 검색 기능 구현
  .env
  pages/_app.tsx
  pages/community/review/index.tsx
  pages/index.tsx
  pages/product/index.tsx
  pages/search/index.tsx
  pages/survey/index.tsx
  src/apis/instance.ts
  src/apis/product.ts
  src/components/Login/apis.ts
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Mypage/apis.ts
  src/components/Product/ProductCard.tsx
  src/components/SignIn/apis.ts
  src/components/common/Image.tsx
  src/components/layout/header/apis.ts
  src/constants/apiUrls.ts
  src/hooks/useLikeList.tsx
  src/hooks/useProduct.tsx
  src/interfaces/base.ts
  src/styles/GlobalStyle.tsx
  src/utils/format.ts
Labels: feature

#66 [커뮤니티] 후기 작성 페이지 구현
  package-lock.json
  package.json
  pages/community/notice/index.tsx
  pages/community/review/add.tsx
  public/icons/arrow-left.svg
  src/components/common/Editor.tsx
Labels: feature

#70 상품 필터링 검색 기능 구현
  package-lock.json
  package.json
  pages/product/index.tsx
  pages/search/index.tsx
  src/apis/product.ts
  src/components/common/Modal.tsx
  src/constants/apiUrls.ts
  src/constants/routes.ts
  src/hooks/useProduct.tsx
Labels: feature

#72 [관리자페이지] /admin/user 페이지 기능 추가
  package-lock.json
  package.json
  pages/admin/user/[id].tsx
  pages/admin/user/index.tsx
  src/components/Admin/Order/OrderTable.tsx
  src/components/Admin/User/AdminTable.tsx
  src/components/Admin/User/TableSearch.tsx
  src/components/Admin/User/UserTable.tsx
  src/components/Admin/User/userColumns.ts
  src/components/Order/OrderItem.tsx
  src/mocks/handlers/productDetail.ts
  src/react-table-config.d.ts
Labels: feature

#73 [커뮤니티] 후기 페이지 구현 중 & 에디터 변경
  package-lock.json
  package.json
  pages/community/review/[id].tsx
  pages/community/review/add.tsx
  pages/community/review/edit.tsx
  pages/product/[id].tsx
  src/components/Community/ReviewItem.tsx
  src/components/common/Editor.tsx
  src/dummydata/reviewDetail.json
  src/interfaces/community.ts
  src/utils/format.ts
Labels: feature

#74 [커뮤니티]후기 목록 api 연결
  pages/community/review/index.tsx
  src/apis/community.ts
  src/constants/apiUrls.ts
Labels: feature

#77 [커뮤니티]후기 상세 페이지 구현중
  pages/community/review/[id].tsx
  src/dummydata/reviewDetail.json
Labels: feature

#78 [커뮤니티] 후기 수정 페이지 api 연결
  pages/community/review/edit.tsx
  src/apis/community.ts
  src/constants/apiUrls.ts
Labels: feature

#81 [커뮤니티] 후기 상세 페이지 구현
  pages/community/review/[id].tsx
  pages/community/review/edit.tsx
  pages/community/review/index.tsx
  src/apis/community.ts
  src/components/Community/ReviewItem.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
Labels: feature

#82 [커뮤니티] 후기 목록 페이지 수정
  pages/community/review/edit.tsx
  pages/community/review/index.tsx
  src/components/Community/ReviewItem.tsx
  src/constants/messages.ts
Labels: feature

#80 [관리자페이지] 사용자 상세정보 수정/관리자 설정 가능
  pages/admin/user/[id].tsx
  src/components/Admin/User/AdminTable.tsx
  src/components/Admin/User/AdminUserInput.tsx
  src/components/Admin/User/AdminUserPassportInput.tsx
  src/components/Admin/User/AdminUserRadio.tsx
  src/components/Admin/User/NotChangeInput.tsx
  src/components/Admin/User/RoleChange.tsx
  src/components/Admin/User/TableSearch.tsx
  src/components/Admin/User/UserTable.tsx
  src/components/Admin/User/userColumns.ts
Labels: feature, style

#86 [커뮤니티] 후기 작성 에디터 변경
  package-lock.json
  package.json
  pages/community/review/add.tsx
  pages/community/review/edit.tsx
  src/components/common/Editor.tsx
Labels: feature, fix

#87 배포 작업
  package-lock.json
  package.json
  pages/admin/user/[id].tsx
  pages/community/notice/[id].tsx
  pages/community/notice/index.tsx
  pages/community/review/add.tsx
  pages/community/review/edit.tsx
  pages/community/review/index.tsx
  src/apis/community.ts
  src/components/Admin/User/AdminTable.tsx
  src/components/Admin/User/AdminUserInput.tsx
  src/components/Admin/User/AdminUserPassportInput.tsx
  src/components/Admin/User/AdminUserRadio.tsx
  src/components/Admin/User/NotChangeInput.tsx
  src/components/Admin/User/RoleChange.tsx
  src/components/Admin/User/TableSearch.tsx
  src/components/Admin/User/UserTable.tsx
  src/components/Admin/User/userColumns.ts
  src/components/Community/NoticeItem.tsx
  src/components/Community/ReviewItem.tsx
  src/components/common/Editor.tsx
  src/constants/apiUrls.ts
Labels: deploy

#88 배포 작업
  pages/cart/index.tsx
Labels: deploy

#89 배포 작업
  pages/index.tsx
Labels: deploy

#90 [관리자페이지] 관리자 유저관리 페이지 에러 해결
  package-lock.json
  pages/admin/index.tsx
  pages/admin/user/index.tsx
  src/components/Admin/User/AdminTable.tsx
  src/components/Admin/User/UserTable.tsx
  src/components/layout/Header.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/Search_header.tsx
Labels: fix

#91 [마이페이지] 예약 내역 화면 구현
  .env
  pages/mypage/order/index.tsx
  pages/mypage/reservation.tsx
  public/icons/arrowRight.svg
  src/apis/mypage/order.ts
  src/components/Mypage/Order/PastOrder.tsx
  src/components/Mypage/Order/ScheduledOrder.tsx
  src/constants/apiUrls.ts
  src/constants/routes.ts
  src/dummydata/orderDetail.json
  src/dummydata/orderList.json
  src/interfaces/myorder.ts
  src/interfaces/mypageOrder.ts
Labels: feature

#94 관리자 페이지 상품 등록 구현
  package-lock.json
  package.json
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/edit.tsx
  pages/admin/product/index.tsx
  pages/admin/product/recommend/index.tsx
  pages/product/index.tsx
  src/apis/admin/product.ts
  src/apis/common.ts
  src/apis/instance.ts
  src/components/Admin/Order/OrderTable.tsx
  src/components/common/AdminTableBody.tsx
  src/components/common/AdminTableRow.tsx
  src/components/common/Editor.tsx
  src/constants/apiUrls.ts
  src/interfaces/product.ts
  src/utils/format.ts
Labels: feature

#97 [관리자 페이지] 상품 목록 페이지네이션 구현
  pages/admin/product/index.tsx
  src/apis/admin/product.ts
  src/constants/apiUrls.ts
Labels: feature

#100 [관리자 페이지] 상품 상세 페이지 수정
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/edit.tsx
  pages/admin/product/index.tsx
  pages/admin/product/recommend/index.tsx
  src/apis/admin/category.ts
  src/apis/admin/recommend.ts
  src/constants/apiUrls.ts
Labels: feature, style

#95 [레이아웃] Header, Footer 생성 (Aside 진행 중)
  package-lock.json
  pages/_app.tsx
  public/icons/FooterCommunity.svg
  public/icons/FooterCommunityBold.svg
  public/icons/FooterHome.svg
  public/icons/FooterHomeBold.svg
  public/icons/FooterMy.svg
  public/icons/FooterMyBold.svg
  public/icons/FooterSearch.svg
  public/icons/FooterSearchBold.svg
  public/icons/HeaderCart.svg
  public/icons/HeaderMenu.svg
  public/icons/HeaderSearch.svg
  src/components/Admin/User/AdminTable.tsx
  src/components/common/ScrollTop.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/footer/Tab.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/MenuList.tsx
  src/components/layout/header/MyCartHeader.tsx
  src/components/layout/header/SearchHeader.tsx
  src/components/layout/header/Search_header.tsx
Labels: style

#102 [관리자 페이지] 상품 추가 시 카테고리 및 상품옵션 추가 구현
  pages/admin/product/add.tsx
  src/apis/admin/category.ts
  src/components/layout/Header.tsx
  src/constants/apiUrls.ts
  src/interfaces/product.ts
Labels: feature

#104 배포 작업을 위한 에러 수정
  pages/admin/product/edit.tsx
  pages/mypage/reservation.tsx
  src/components/layout/Header.tsx
Labels: fix

#105 [관리자 페이지] 상품 추가 카테고리 관련 수정
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  src/components/layout/Header.tsx
  src/utils/format.ts
Labels: feature

#106 배포 작업
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  src/components/layout/Header.tsx
  src/utils/format.ts
Labels: deploy

#108 [레이아웃]레이아웃 완료(라우터 제외)
  pages/login/index.tsx
  src/components/common/ScrollTop.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/footer/Tab.tsx
  src/components/layout/header/MenuList.tsx
  src/components/layout/nav/AsideNav.tsx
  src/components/layout/nav/Depth1.tsx
  src/components/layout/nav/Depth2.tsx
  src/components/layout/nav/Depth3.tsx
  src/components/layout/nav/NavCateD1.tsx
  src/constants/layoutRoutes.ts
  src/constants/navGroup.ts
Labels: style

#109 메인 페이지 구현
  .env
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/mypage/review/index.tsx
  public/icons/ArrowRightWhite.svg
  public/main.svg
  src/apis/main.ts
  src/components/Main/Banner.tsx
  src/components/Main/BannerList.tsx
  src/components/Main/BestProducts.tsx
  src/components/Main/GroupProduct.tsx
  src/components/Main/GroupTrip.tsx
  src/components/Main/PopularRegion.tsx
  src/constants/apiUrls.ts
  src/dummydata/bannerList.json
  src/dummydata/groupProduct.json
  src/dummydata/productDetail.json
  src/interfaces/main.ts
Labels: feature

#111 상품 검색 및 목록 페이지 구현
  pages/product/index.tsx
  src/apis/product.ts
  src/components/Search/Search.tsx
  src/components/layout/header/SearchHeader.tsx
  src/components/layout/nav/NavCateD1.tsx
  src/constants/apiUrls.ts
Labels: feature

#114 [로그인 페이지] 메시지 에러
  pages/404/index.tsx
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/index.tsx
  pages/login/index.tsx
  public/lotties/404page.json
  src/apis/admin/product.ts
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/product.ts
  src/utils/format.ts
Labels: fix

#115 [로그인페이지] 에러 해결
  package-lock.json
  pages/mypage/info/index.tsx
  pages/signup/index.tsx
  src/components/Main/PopularRegion.tsx
Labels: fix

#117 상품 상세 페이지 구현
  pages/_app.tsx
  pages/index.tsx
  pages/product/[id].tsx
  src/apis/product.ts
  src/apis/wishlist.ts
  src/components/Main/PopularRegion.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/dummydata/productDetail.json
  src/dummydata/relatedProducts.json
  src/dummydata/wishList.json
  src/interfaces/product.ts
  src/interfaces/wishlist.ts
Labels: feature

#122 [회원가입 페이지] css 작업, api 기능 복구
  pages/_app.tsx
  pages/signup/index.tsx
  src/components/Login/apis.ts
  src/components/SignIn/CheckPassword.tsx
  src/components/SignIn/EmailInput.tsx
  src/components/SignIn/GenderInput.tsx
  src/components/SignIn/PassportInput.tsx
  src/components/SignIn/apis.ts
  src/components/common/Input.tsx
  src/components/layout/header/Logo.tsx
  src/constants/messages.ts
Labels: fix, style

#123 나의 관심 상품 구현중
  pages/mypage/wish/index.tsx
  src/apis/mypage/wish.ts
  src/components/Mypage/Wish/WishCard.tsx
  src/constants/apiUrls.ts
  src/constants/routes.ts
  src/interfaces/wishlist.ts
Labels: feature

#125 장바구니 기능 구현중 및 리드미 파일 수정
  README.md
  package-lock.json
  pages/cart/index.tsx
  src/apis/cart.ts
Labels: feature, docs

#126 여행 유형 테스트 시 필수로 답변 선택하도록 수정
  pages/survey/index.tsx
  src/constants/messages.ts
Labels: feature, fix

#127 [관리자] 배너 관리 구현
  package-lock.json
  package.json
  pages/admin/banner/[id].tsx
  pages/admin/banner/add.tsx
  pages/admin/banner/edit.tsx
  pages/admin/banner/index.tsx
  pages/admin/community/notice/[id].tsx
  pages/admin/community/notice/edit.tsx
  pages/admin/community/notice/index.tsx
  pages/admin/community/review/[id].tsx
  pages/admin/community/review/edit.tsx
  pages/admin/community/review/index.tsx
  pages/community/notice/index.tsx
  pages/community/review/index.tsx
  pages/mypage/order/index.tsx
  pages/mypage/review/[id].tsx
  pages/mypage/review/index.tsx
  pages/product/[id].tsx
  src/apis/admin/banner.ts
  src/apis/admin/product.ts
  src/apis/community.ts
  src/apis/wishlist.ts
  src/components/Admin/banner/BannerList.tsx
  src/components/Community/CommunityRouter.tsx
  src/components/Main/Banner.tsx
  src/components/Main/BannerList.tsx
  src/components/Main/BestProducts.tsx
  src/components/Main/GroupProduct.tsx
  src/components/Main/GroupTrip.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/banner.ts
Labels: feature

#128 [레이아웃] 검색페이지 헤더 수정/ 라우터 수정/ 리프레시 토큰 시간 수정
  pages/_app.tsx
  src/components/common/Input.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/nav/Depth2.tsx
  src/components/layout/nav/Depth3.tsx
  src/components/layout/nav/NavCateD1.tsx
Labels: fix, style

#130 [마이페이지] 관심 상품 페이지 구현
  pages/mypage/wish/index.tsx
  src/apis/mypage/wish.ts
  src/components/Mypage/Wish/WishCard.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/store/index.tsx
  src/store/wish.tsx
Labels: feature

#131 상품 상세 페이지 - 위시리스트 관련 수정
  pages/community/notice/index.tsx
  pages/product/[id].tsx
  src/apis/wishlist.ts
  src/components/Main/Banner.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
Labels: feature

#132 리드미 파일 수정
  README.md
Labels: feature, docs

#133 장바구니 기능 구현중
  pages/cart/index.tsx
  src/apis/cart.ts
  src/components/Cart/CartCard.tsx
  src/constants/apiUrls.ts
  src/interfaces/cart.ts
  src/store/cart.tsx
  src/utils/format.ts
Labels: feature

#134 [레이아웃] 리프레시 토큰 api 수정
  src/components/layout/header/apis.ts
Labels: fix

#135 [리드미] 리드미 작성
  README.md
Labels: docs

#136 배포 작업
  README.md
  pages/admin/product/[id].tsx
  pages/admin/product/edit.tsx
  pages/admin/product/index.tsx
  pages/admin/product/recommend/index.tsx
  pages/cart/index.tsx
  pages/community/notice/index.tsx
  pages/mypage/wish/index.tsx
  pages/product/[id].tsx
  src/apis/admin/category.ts
  src/apis/admin/product.ts
  src/apis/admin/recommend.ts
  src/apis/cart.ts
  src/apis/mypage/wish.ts
  src/apis/wishlist.ts
  src/components/Cart/CartCard.tsx
  src/components/Main/Banner.tsx
  src/components/Main/BestProducts.tsx
  src/components/Main/GroupProduct.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Order/OrderItem.tsx
  src/components/layout/header/apis.ts
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/constants/routes.ts
  src/interfaces/cart.ts
  src/interfaces/product.ts
  src/store/cart.tsx
  src/store/index.tsx
  src/store/wish.tsx
  src/utils/format.ts
Labels: deploy

#139 에디터 관련 에러 수정
  src/components/common/Editor.tsx
Labels: fix, deploy

#140 에디터 관련 에러 수정 및 배포 작업
  pages/admin/community/notice/add.tsx
  pages/admin/community/notice/edit.tsx
  pages/admin/community/review/add.tsx
  pages/admin/community/review/edit.tsx
  pages/admin/product/add.tsx
  pages/admin/product/edit.tsx
  pages/community/review/add.tsx
  pages/community/review/edit.tsx
  src/components/common/Editor.tsx
Labels: fix, deploy

#141 장바구니 기능 구현
  pages/cart/index.tsx
  public/icons/survey/userMinus.svg
  public/icons/survey/userPlus.svg
  src/apis/cart.ts
  src/components/Cart/CartCard.tsx
  src/constants/messages.ts
  src/interfaces/cart.ts
  src/store/cart.tsx
Labels: feature

#142 모든 상품 id 를 number 타입으로 변경 / api 호출 부분에 try-catch 추가
  pages/admin/community/notice/index.tsx
  pages/admin/community/review/index.tsx
  pages/admin/product/index.tsx
  pages/cart/index.tsx
  pages/mypage/wish/index.tsx
  pages/product/[id].tsx
  pages/product/index.tsx
  pages/survey/index.tsx
  src/apis/main.ts
  src/apis/product.ts
  src/components/Admin/banner/BannerList.tsx
  src/components/Cart/CartCard.tsx
  src/components/Main/BestProducts.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/constants/routes.ts
  src/interfaces/wish.ts
  src/store/wish.tsx
Labels: feature, refactor

#144 공통 메시지 상수 파일 수정
  pages/community/review/[id].tsx
  pages/community/review/index.tsx
  pages/mypage/order/[id].tsx
  src/components/Mypage/apis.ts
  src/components/Search/Search.tsx
  src/components/common/PasswordModal.tsx
  src/constants/messages.ts
Labels: refactor

#145 공통 api 호출 url 상수 파일 수정
  pages/product/[id].tsx
  src/apis/cart.ts
  src/apis/community.ts
  src/apis/main.ts
  src/apis/mypage/order.ts
  src/apis/mypage/review.ts
  src/apis/mypage/wish.ts
  src/apis/product.ts
  src/apis/user.ts
  src/apis/wish.ts
  src/apis/wishlist.ts
  src/constants/apiUrls.ts
  src/interfaces/cart.ts
Labels: feature, refactor

#146 장바구니 삭제 기능 구현
  pages/cart/index.tsx
  src/components/Cart/CartCard.tsx
  src/store/cart.tsx
Labels: feature

#147 배너 관련 수정 및 메인 cursor 추가
  pages/admin/banner/[id].tsx
  pages/admin/banner/add.tsx
  pages/admin/banner/edit.tsx
  pages/index.tsx
  pages/product/[id].tsx
  src/components/Main/Banner.tsx
  src/components/Main/BestProducts.tsx
  src/components/Main/GroupProduct.tsx
  src/components/Main/GroupTrip.tsx
  src/components/Main/PopularRegion.tsx
  src/dummydata/bannerList.json
  src/interfaces/banner.ts
  src/interfaces/main.ts
Labels: feature, style, refactor

#148 api 호출 함수명 통일
  pages/admin/product/add.tsx
  pages/admin/product/edit.tsx
  pages/product/[id].tsx
  pages/survey/index.tsx
  src/apis/admin/category.ts
  src/apis/admin/product.ts
  src/apis/admin/recommend.ts
  src/apis/cart.ts
  src/apis/user.ts
  src/components/Cart/CartCard.tsx
  src/interfaces/base.ts
  src/interfaces/product.ts
Labels: refactor

#149 [관리자 페이지] 추천 상품 관리 구현
  pages/admin/product/add.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/edit.tsx
  pages/admin/product/index.tsx
  pages/admin/product/recommend/[id].tsx
  pages/admin/product/recommend/add.tsx
  pages/admin/product/recommend/edit.tsx
  pages/admin/product/recommend/index.tsx
  src/apis/admin/recommend.ts
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/product.ts
Labels: feature

#150 커뮤니티 페이지 관련 수정
  pages/community/notice/[id].tsx
  pages/community/notice/index.tsx
  pages/community/review/[id].tsx
  pages/community/review/index.tsx
  src/components/Community/CommunityRouter.tsx
  src/components/Community/NoticeItem.tsx
  src/components/Community/ReviewItem.tsx
Labels: feature, fix, style, refactor

#152 카카오맵 key 추가
  .env
Labels: chore

#153 검색 컴포넌트 호출 추천 상품 api url 수정
  pages/admin/product/recommend/edit.tsx
  src/apis/product.ts
Labels: fix

#154 배포 작업
  .env
  pages/admin/product/recommend/edit.tsx
  src/apis/product.ts
Labels: deploy

#155 [마이페이지] 마이페이지 메인/ 마이페이지 내 정보 보기
  README.md
  pages/mypage/info/index.tsx
  public/icons/Withdrawal.svg
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Info/NotInput.tsx
  src/components/Mypage/Info/NotInputGender.tsx
  src/components/Mypage/Info/NotInputPassport.tsx
  src/components/Mypage/Logout.tsx
  src/components/Mypage/Withdrawal.tsx
  src/components/Mypage/apis.ts
  src/components/Mypage/function.ts
  src/components/common/Input.tsx
  src/components/common/NotInput.tsx
  src/components/layout/Header.tsx
  src/components/layout/MyPageNavbar.tsx
  src/components/layout/Navbar.tsx
  src/constants/layoutRoutes.ts
  src/interfaces/myinfo.ts
Labels: fix, style

#156 [관리자 페이지] 상품 카테고리 관리 구현
  README.md
  pages/admin/product/category/[id].tsx
  pages/admin/product/category/add.tsx
  pages/admin/product/category/edit.tsx
  pages/admin/product/category/index.tsx
  src/apis/admin/category.ts
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/product.ts
Labels: feature

#158 [결제페이지] api 연동, css 작업
  package-lock.json
  pages/order/index.tsx
  pages/order/success.tsx
  src/components/layout/nav/NavCateD1.tsx
Labels: feature, style

#161 상품 목록에 태그 추가 / 모바일 검색 페이지 레이아웃 수정 / 여행 유형 테스트 결과 텍스트 추가
  pages/_document.tsx
  pages/product/index.tsx
  pages/survey/index.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Product/ProductCard.tsx
  src/components/Product/SurveyProductCard.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/MyCartHeader.tsx
  src/interfaces/product.ts
  src/utils/format.ts
Labels: feature, refactor

#160 [관리자 페이지] 예약관리 css, api 작업
  pages/admin/order/index.tsx
  pages/signup/success.tsx
  src/components/Admin/Order/AdminOrderTable.tsx
  src/components/Admin/Order/orderColumns.ts
  src/components/Admin/User/UserTable.tsx
  src/components/Login/apis.ts
  src/components/SignIn/apis.ts
Labels: feature, style

#162 [관리자 페이지] 상품 수정 및 옵션 등록/수정/삭제 구현
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  pages/admin/product/edit.tsx
  pages/admin/product/recommend/edit.tsx
  src/apis/admin/product.ts
  src/components/common/Modal.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/styles/GlobalStyle.tsx
  src/utils/format.ts
Labels: feature

#163 배포 작업
  README.md
  package-lock.json
  pages/_document.tsx
  pages/admin/order/index.tsx
  pages/admin/product/[id].tsx
  pages/admin/product/add.tsx
  pages/admin/product/category/[id].tsx
  pages/admin/product/category/add.tsx
  pages/admin/product/category/edit.tsx
  pages/admin/product/category/index.tsx
  pages/admin/product/edit.tsx
  pages/admin/product/recommend/edit.tsx
  pages/mypage/info/index.tsx
  pages/order/index.tsx
  pages/order/success.tsx
  pages/product/index.tsx
  pages/signup/success.tsx
  pages/survey/index.tsx
  public/icons/Withdrawal.svg
  src/apis/admin/category.ts
  src/apis/admin/product.ts
  src/components/Admin/Order/AdminOrderTable.tsx
  src/components/Admin/Order/orderColumns.ts
  src/components/Admin/User/UserTable.tsx
  src/components/Login/apis.ts
  src/components/Main/BestProducts.tsx
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Info/NotInput.tsx
  src/components/Mypage/Info/NotInputGender.tsx
  src/components/Mypage/Info/NotInputPassport.tsx
  src/components/Mypage/Logout.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Mypage/Withdrawal.tsx
  src/components/Mypage/apis.ts
  src/components/Mypage/function.ts
  src/components/Product/ProductCard.tsx
  src/components/Product/SurveyProductCard.tsx
  src/components/SignIn/apis.ts
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/NotInput.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MyPageNavbar.tsx
  src/components/layout/header/MyCartHeader.tsx
  src/components/layout/nav/NavCateD1.tsx
  src/constants/apiUrls.ts
  src/constants/layoutRoutes.ts
  src/constants/messages.ts
  src/interfaces/myinfo.ts
  src/interfaces/product.ts
  src/styles/GlobalStyle.tsx
  src/utils/format.ts
Labels: deploy

#164 상품 상세 페이지 공유하기 추가 및 더미데이터 삭제
  package-lock.json
  package.json
  pages/_document.tsx
  pages/product/[id].tsx
  src/components/Mypage/Order/PastOrder.tsx
  src/components/Mypage/Order/ScheduledOrder.tsx
  src/components/apis/admin/banner.ts
  src/components/apis/admin/category.ts
  src/components/apis/admin/product.ts
  src/components/apis/admin/recommend.ts
  src/components/apis/cart.ts
  src/components/apis/common.ts
  src/components/apis/community.ts
  src/components/apis/instance.ts
  src/components/apis/main.ts
  src/components/apis/mypage/order.ts
  src/components/apis/mypage/review.ts
  src/components/apis/mypage/wish.ts
  src/components/apis/product.ts
  src/components/apis/user.ts
  src/components/apis/wishlist.ts
  src/components/common/Modal.tsx
  src/dummydata/MyReviewList.json
  src/dummydata/bannerList.json
  src/dummydata/communityNotice.json
  src/dummydata/communityReview.json
  src/dummydata/groupProduct.json
  src/dummydata/orderDetail.json
  src/dummydata/orderList.json
  src/dummydata/productDetail.json
  src/dummydata/relatedProducts.json
  src/dummydata/reviewDetail.json
  src/dummydata/wishList.json
  src/store/modal.tsx
Labels: feature, refactor, chore

#165 [리팩토링] api 분리, console.log 삭제, functions 분리
  pages/admin/order/index.tsx
  pages/admin/user/[id].tsx
  pages/admin/user/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/mypage/info/index.tsx
  pages/order/index.tsx
  pages/signup/index.tsx
  pages/signup/success.tsx
  src/apis/admin/order.ts
  src/apis/admin/user.ts
  src/apis/layout.ts
  src/apis/login.ts
  src/apis/mypage/info.ts
  src/apis/order.ts
  src/apis/signup.ts
  src/components/Admin/Order/AdminOrderTable.tsx
  src/components/Admin/Order/OrderTable.tsx
  src/components/Admin/User/AdminUserInput.tsx
  src/components/Admin/User/AdminUserPassportInput.tsx
  src/components/Admin/User/AdminUserRadio.tsx
  src/components/Admin/User/NotChangeInput.tsx
  src/components/Admin/User/RoleChange.tsx
  src/components/Admin/User/UserTable.tsx
  src/components/Mypage/GetMyinfo.tsx
  src/components/Mypage/Logout.tsx
  src/components/Order/OrderItem.tsx
  src/components/SignIn/EmailInput.tsx
  src/components/common/Input.tsx
  src/components/common/PasswordModal.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/LoginHeader.tsx
  src/components/layout/header/MypageHeader.tsx
  src/components/layout/mobileNav/Tab.tsx
  src/components/layout/nav/AsideNav.tsx
  src/components/layout/nav/Depth2.tsx
  src/components/layout/nav/FlexGroup.tsx
  src/components/layout/nav/HoverGroup.tsx
  src/components/layout/nav/NavCateD1.tsx
  src/components/layout/nav/NavList.tsx
  src/utils/check.ts
  src/utils/globalAge.ts
Labels: feature, refactor, chore

#166 내브바 레이아웃 수정 / 관심 상품 목록 레이아웃 수정
  package-lock.json
  pages/index.tsx
  pages/mypage/info/index.tsx
  pages/mypage/wish/index.tsx
  pages/survey/index.tsx
  src/components/Cart/CartCard.tsx
  src/components/Mypage/Wish/WishCard.tsx
  src/components/Product/ProductCard.tsx
  src/components/layout/Header.tsx
  src/components/layout/MyPageNavbar.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/MyCartHeader.tsx
  src/components/layout/header/SearchHeader.tsx
  src/constants/layoutRoutes.ts
Labels: style, refactor
